services:
  redis:
    image: redis:latest
    container_name: hash-redis
    restart: always
    ports:
      - "6380:6379"
    env_file:
      - ./.env
    volumes:
      - ./app/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  web:
    build: .
    container_name: hash-web
    restart: always
    ports:
      - "5004:8000"
    depends_on:
      - redis
    env_file:
      - ./.env
    volumes:
      - ./app:/app
      - ./flag.txt:/flag.txt:ro